from mn import analysis as a

########################################################################################################################
#                  THIS IS THE MAIN EXECUTION SCRIPT FOR THE ANALYSIS PIPELINE OUTLINED IN README.MD
#
#   a)  Strings in [stories] should correspond to names of audio files of narratives so they can be used in the following
#       convention NAME_audio.wav; ideally, you also have NAME_transcript.txt in ./text/text_to_be_segmented/NAME/
#   b)  For now, we are not using segments, but if these are needed, then uncomment blocks in the first level analysis
#       functions for segments and drop segment .txt files into ./text/segments/NAME/
#   c)  The NAME strings will also create directories in ./text/timestamps/ and files that use NAME in that
#       directory--those will be generated by mn.analysis.transcribe() (which can also be run from here)
#   d)  After running the transcription script for the audio file, change to python 3.8 and follow instructions from
#       getMAC_MFT.py.  Execute it for each story you generated files for in ./text/timestamps
#   e)  Switch back to Python 3.12 with all latest libraries needed to run this code and build a loop or execute single
#       scripts one-by-one.
#   f)  mn.analysis.univariateWithMask(story, mask) takes a string for 'mask,' which should be a .nii.gz in ./masks/
#   g)  It is optional but advised to use mn.analysis.downloadStory(NAME)/dropStory(NAME) to maintain space on Disk,
#       so put those into the main loop over narratives/stories AFTER all modelling/transcription/scoring done.
#   f)  prettymouth should be downloaded and dropped as prettymouth but modelled using prettymouthaffair and
#       prettymouthparanoia for the two groups in the experiment. excluded.xlsx has the group definitions
#
########################################################################################################################

#stories = ['forgot','21styear','slumlordreach','bronx','pieman','piemanpni','tunnel', 'black','lucy','merlin','shapesphysical', 'shapessocial','notthefallintact','milkywayoriginal','milkywaysynonyms','milkywayvodka']
stories = ['prettymouthparanoia']

masks = [
         'gyrus_stg_association-test_z_FDR_0.01.nii',
         'antSTG_MTG_HOonly_L.nii.gz',
         'antSTG_MTG_HOonly_R.nii.gz',
         'antSTG_MTG_refined_mask_L.nii.gz',
         'antSTG_MTG_refined_mask_R.nii.gz',
         'posSTG_MTG_HOonly_L.nii.gz',
         'posSTG_MTG_HOonly_R.nii.gz',
         'posSTG_MTG_refined_mask_L.nii.gz',
         'posSTG_MTG_refined_mask_R.nii.gz',
         'STG_MTG_refined_mask_L.nii.gz',
         'STG_MTG_refined_mask_R.nii.gz',
         'tempPole_HOonly_L.nii.gz',
         'tempPole_HOonly_R.nii.gz'
         ]

for story in stories:

    a.firstLevelMacVices(story)
    a.firstLevelMacVirtues(story)
    a.secondLevelMacVices(story)
    a.secondLevelMacVirtues(story)
    a.secondLevelMacVices_1v6(story)
    a.secondLevelMacVirtues_1v6(story)
    a.secondLevelMacVices_1vB(story)
    a.secondLevelMacVirtues_1vB(story)
    for mask in masks:
        a.univariateWithMask(story, mask)
#
