from mn import analysis as a
#import getMAC_MFT_by_seconds
import warnings
warnings.filterwarnings("ignore")
########################################################################################################################
#                  THIS IS THE MAIN EXECUTION SCRIPT FOR THE ANALYSIS PIPELINE OUTLINED IN README.MD
#
#   a)  Strings in [stories] should correspond to names of audio files of narratives so they can be used in the following
#       convention NAME_audio.wav; ideally, you also have NAME_transcript.txt somewhere for sanity checks.
#   b)  For now, we are not using segments, but if these are needed, then uncomment blocks in the first level analysis
#       functions for segments and drop segment .txt files into ./text/segments/NAME/ [in olderAnalysis]
#   c)  The NAME strings will also create directories in ./text/timestamps/ and files that use NAME in that
#       directory--those will be generated by mn.analysis.transcribe() (which can also be run from here)
#   d)  After running the transcription script for the audio file, change to python 3.8 and follow instructions from
#       getMAC_MFT_by_seconds.py.  Execute it for each story you generated files for in ./text/timestamps
#   e)  Switch back to Python 3.12 with all latest libraries needed to run this code and build a loop or execute single
#       scripts one-by-one.
#   f)  mn.analysis.univariateWithMask takes a 'mask,' which should be a .nii.gz in ./masks/
#   g)  It is optional but advised to use mn.analysis.downloadStory(NAME)/dropStory(NAME) to maintain space on Disk,
#       so put those into the main loop over narratives/stories AFTER all modelling/transcription/scoring done.
#   h)  prettymouth should be downloaded and dropped as prettymouth but modelled using prettymouthaffair and
#       prettymouthparanoia for the two groups in the experiment. excluded.xlsx has the group definitions
#   i)  milkyway has 3 audio files and should be modelled at the first level as distinct stories; at the second level,
#       it should be modelled as a single story. So, call first level modelling functions with version names and
#       second level modelling functions with 'milkyway' as parameter. Exceptions are built into the code for this
#       and excluded.xlsx there is also a mergeMilkway(directory) helper to copy first level models into a 'milkyway' directory.
#
########################################################################################################################
dir1 = "G:/fMRI_project/processed_3/"
dir2 = "G:/fMRI_project/processed_6/"
#stories = ['prettymouth','sherlock','forgot','21styear','slumlordreach','bronx','pieman','piemanpni','tunnel', 'black','lucy','merlin','shapesphysical', 'shapessocial','notthefallintact','milkywayoriginal','milkywaysynonyms','milkywayvodka','prettymouthaffair','prettymouthparanoia']
#stories = ['prettymouthparanoia']

stories = ['shapessocial','tunnel','21styear','prettymouthaffair','prettymouthparanoia','milkywayoriginal','milkywaysynonyms','milkywayvodka']

masks = [
            'gyrus_stg_association-test_z_FDR_0.01.nii',
            'antSTG_MTG_HOonly_L.nii.gz',
            'antSTG_MTG_HOonly_R.nii.gz',
            'antSTG_MTG_refined_mask_L.nii.gz',
            'antSTG_MTG_refined_mask_R.nii.gz',
            'posSTG_MTG_HOonly_L.nii.gz',
            'posSTG_MTG_HOonly_R.nii.gz',
            'posSTG_MTG_refined_mask_L.nii.gz',
            'posSTG_MTG_refined_mask_R.nii.gz',
            'STG_MTG_refined_mask_L.nii.gz',
            'STG_MTG_refined_mask_R.nii.gz',
            'tempPole_HOonly_L.nii.gz',
            'tempPole_HOonly_R.nii.gz',
            'TPJ_refined_mask_L.nii.gz',
            'TPJ_refined_mask_R.nii.gz',
            'hippocampus_L.nii.gz',
            'hippocampus_R.nii.gz'
         ]

for story in stories:
    # getMAC_MFT_by_seconds.run( story, 3 )
    # getMAC_MFT_by_seconds.run(story, 6)
    a.downloadStory(story)
    a.firstLevelMacVirtues(story, dir1, 3)
    a.firstLevelMacVices(story, dir1, 3)
    a.secondLevelMacVices(story, dir1, 3)
    a.secondLevelMacVirtues(story, dir1, 3)
    a.secondLevelMacVices_1vB(story, dir1, 3)
    a.secondLevelMacVirtues_1vB(story, dir1, 3)
    a.secondLevelMacVirtues_1v6(story, dir1, 3)
    a.secondLevelMacVices_1v6(story, dir1, 3)
    for mask in masks:
        a.univariateWithMask(story, mask, dir1, 3)
    a.firstLevelMacVirtues(story, dir2, 6)
    a.firstLevelMacVices(story, dir2, 6)
    a.secondLevelMacVices(story, dir2, 6)
    a.secondLevelMacVirtues(story, dir2, 6)
    a.secondLevelMacVices_1vB(story, dir2, 6)
    a.secondLevelMacVirtues_1vB(story, dir2, 6)
    a.secondLevelMacVirtues_1v6(story, dir2, 6)
    a.secondLevelMacVices_1v6(story, dir2, 6)
    for mask in masks:
        a.univariateWithMask(story, mask, dir2, 6)
    a.dropStory(story)

