import downloadWithDatalad
# import deleteWithDatalad
# import firstLevelModel_virtues
# import firstLevelModel_vices
# import secondLevelModel_1vB_MAC_virtues
# import secondLevelModel_1v6_MAC_virtues
# import secondLevelModel_1vB_MAC_vices
# import secondLevelModel_1v6_MAC_vices
# import secondLevelModel_virtues
# import secondLevelModel_vices
# import transcribeAudio_x
# import getMAC_MFT
import univariate_withMask

########################################################################################################################
#                  THIS IS THE MAIN EXECUTION SCRIPT FOR THE ANALYSIS PIPELINE OUTLINED IN README.MD
#
#   strings in [stories] should correspond to names of audio files of narratives so they can be used in the following
#   convention NAME_audio.wav; ideally, you also have NAME_transcript.txt in ./text/text_to_be_segmented/NAME/
#   For now, we are not using segments, but if these are needed, then uncomment blocks in the first level analysis
#   programs for segments and drop segment .txt files into ./text/segments/NAME/
#   The NAME strings will also create directories in ./text/timestamps with that name and files that use NAME in that
#   directory--those will be generated by transcribe_audio_x.py (which can also be run from here)
#   After running the transcription script for the audio file, change to python 3.8 and follow instructions from
#   getMAC_MFT.py.  Execute it for each story you generated files for in ./text/timestamps
#   Switch back to Python 3.12 with all latest libraries needed to run this code and build a loop or execute single
#   scripts one-by-one. Each program has a run() function that can be called from here and into which the string from
#   [stories] or should be passed as a parameter.  For second level models 1vB and 1v6 another
#   parameter integer is passed. That integer specifies iteration through foundations; for current programs it is MAC
#   virtues and vices respectively.  These are not generic execution programs; consult comments in them for purpose
#   and use.  Rebuild this program/loop on an as-needed basis for execution.
#
#   Note:   it is optional but advised to use downloadWithDatalad.run(NAME) and deleteWithDatalad.ren(NAME) to maintain
#           space on Disk, so put those into the main loop over narratives/stories AFTER all transcription/scoring done.
#
########################################################################################################################

#stories = ['21styear','tunnel','slumlordreach','pieman','lucy','merlin','shapesphysical', 'shapessocial','notthefallintact','milkywayoriginal','milkywaysynonyms','milkywayvodka']
L_TPJ_mask = "TPJ_refined_mask_L.nii.gz"
R_TPJ_mask = "TPJ_refined_mask_R.nii.gz"
stories = ['forgot','bronx','piemanpni', 'black']

for task in stories:
    # transcribeAudio_x.run(task)
    # getMAC_MFT.run(task)

    downloadWithDatalad.run(task)
    univariate_withMask.run( task, L_TPJ_mask)
    univariate_withMask.run( task, R_TPJ_mask)


    # firstLevelModel_virtues.run(task)
    # firstLevelModel_vices.run(task)
    # secondLevelModel_virtues.run(task)
    # secondLevelModel_vices.run(task)

    # for foundation in range(1,8):
    #     secondLevelModel_1v6_MAC_virtues.run(task, foundation)
    #     secondLevelModel_1vB_MAC_virtues.run(task, foundation)
    #     secondLevelModel_1v6_MAC_vices.run(task, foundation)
    #     secondLevelModel_1vB_MAC_vices.run(task, foundation)
    #
    # deleteWithDatalad.run(task)

